# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!

target 'BKProjectFramework' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BKProjectFramework

pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MJExtension'
pod 'FLAnimatedImage'
pod 'IQKeyboardManager'
pod 'SAMKeychain'
pod 'MBProgressHUD'
pod 'LFLiveKit'

end
